#!/usr/bin/env python3
"""Generate the FineWeb training sweep configs.

Matrix: translator arch {mlp, encoder, flow, sae} x loss {mse, cosine, info_nce}
        x token pooling {last, mean}  =  24 configs, written to config/fineweb/.

Every config shares ONE FineWeb split (HuggingFaceFW/fineweb-edu sample-10BT,
split="train", limit=30000, seed 42 doc-level) and the SAME source/target model
pair, so all 24 runs are trained on exactly the same sentences. Sentences and
activations are cached under data/fineweb/ (shared); only the token pooling
changes the activation cache (last-token vs mean-pooled), and model_slug tags the
mean caches with `_mean` so the two never collide. Translator checkpoints +
TensorBoard logs go to outputs/fineweb/.

Re-run this script any time to regenerate the configs from scratch.
"""

from pathlib import Path

from sweep_common import LIMIT, TRANSLATOR_BLOCKS, base_blocks, training_block

OUT_DIR = Path(__file__).resolve().parent / "fineweb"

LOSSES = ["mse", "cosine", "info_nce"]
POOLINGS = {"last": "-1", "mean": '"mean"'}  # token_position value, verbatim TOML


def make_config(arch: str, loss: str, pool: str) -> str:
    return f"""# AUTO-GENERATED by config/generate_fineweb_configs.py — do not edit by hand.
# FineWeb sweep: translator={arch}  loss={loss}  token={pool}
# Shared FineWeb split (sample-10BT, seed 42, limit {LIMIT}); cache pinned to HF_CACHE_DIR.

{base_blocks(POOLINGS[pool])}
[translator]
{TRANSLATOR_BLOCKS[arch]}

{training_block([loss], [1.0], arch,
                "translator checkpoints + tensorboard logs",
                "sentences.json + activation caches (shared by all 24)")}"""


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for arch in TRANSLATOR_BLOCKS:
        for loss in LOSSES:
            for pool in POOLINGS:
                name = f"{arch}_{loss}_{pool}.toml"
                (OUT_DIR / name).write_text(make_config(arch, loss, pool))
                written.append(name)
    print(f"Wrote {len(written)} configs to {OUT_DIR}/")
    for n in written:
        print(f"  {n}")


if __name__ == "__main__":
    main()
