#!/usr/bin/env python3
"""Generate the FineWeb training sweep configs.

Matrix: translator arch {mlp, encoder, flow, sae} x loss {mse, cosine, info_nce}
        x token pooling {last, mean}  =  24 configs, written to config/fineweb/.

Every config shares ONE FineWeb split (HuggingFaceFW/fineweb-edu sample-10BT,
split="train", limit=30000, seed 42 doc-level) and the SAME source/target model
pair, so all 24 runs are trained on exactly the same sentences. Sentences and
activations are cached under data/fineweb/ (shared); only the token pooling
changes the activation cache (last-token vs mean-pooled), and model_slug tags the
mean caches with `_mean` so the two never collide. Translator checkpoints +
TensorBoard logs go to outputs/fineweb/.

Re-run this script any time to regenerate the configs from scratch.
"""

from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent / "fineweb"

SOURCE_NAME = "meta-llama/Llama-3.2-1B-Instruct"
TARGET_NAME = "meta-llama/Llama-3.2-3B-Instruct"
LAYER = 8
LIMIT = 30000

LOSSES = ["mse", "cosine", "info_nce"]
POOLINGS = {"last": "-1", "mean": '"mean"'}  # token_position value, verbatim TOML

# Per-architecture [translator] block (everything below the `type` line).
TRANSLATOR_BLOCKS = {
    "mlp": """type = "mlp"
hidden_dims = [2048, 2048, 2048]
dropout = 0.1
activation = "gelu"
use_residual = false""",
    "encoder": """type = "encoder"
d_model = 512
nhead = 8
num_layers = 4
dropout = 0.1""",
    "flow": """type = "flow"
num_blocks = 8           # stacked [ActNorm -> mixing -> AffineCoupling] blocks
coupling_hidden = 1024
activation = "gelu"
mixing = "permutation"   # "permutation" (stable) | "inv1x1" (Glow, can blow up at large D)""",
    "sae": """type = "sae"
latent_dim = 16384         # 8x overcomplete bottleneck (8 * 2048)
sae_activation = "topk"    # "topk" (architectural sparsity) | "l1" (penalty-based)
k = 64
l1_coeff = 1e-3
normalize_decoder = true""",
}


def training_block(loss: str, arch: str) -> str:
    extra = ""
    if arch == "flow":
        # A reversible flow learns target->source for free; supervise it too.
        extra = "\ninverse_loss_weight = 1.0"
    return f"""[training]
epochs = 1000
batch_size = 2048
lr = 1e-4
weight_decay = 1e-4
train_ratio = 0.8
seed = 42
output_dir = "outputs/fineweb"   # translator checkpoints + tensorboard logs
data_dir = "data/fineweb"        # sentences.json + activation caches (shared by all 24)
normalize_activations = true
losses = ["{loss}"]
loss_weights = [1.0]
temperature = 0.1
grad_clip = 1.0
lr_warmup_epochs = 10
early_stopping_patience = 50
early_stopping_min_delta = 1e-4{extra}
"""


def make_config(arch: str, loss: str, pool: str) -> str:
    tp = POOLINGS[pool]
    return f"""# AUTO-GENERATED by config/generate_fineweb_configs.py — do not edit by hand.
# FineWeb sweep: translator={arch}  loss={loss}  token={pool}
# Shared FineWeb split (sample-10BT, seed 42, limit {LIMIT}); cache pinned to HF_CACHE_DIR.

batch_size = 32   # activation-extraction batch size

[source_model]
name = "{SOURCE_NAME}"
layer = {LAYER}
module = "residual"
token_position = {tp}

[target_model]
name = "{TARGET_NAME}"
layer = {LAYER}
module = "residual"
token_position = {tp}

[dataset]
name = "FINEWEB"
behaviors = []          # unused for FINEWEB
split = "train"         # "train"/"generate" -> 80% ; "test" -> 20% (seed 42, doc-level)
data_root = ""          # unused for FINEWEB; subset fixed to fineweb-edu/sample-10BT
limit = {LIMIT}

[translator]
{TRANSLATOR_BLOCKS[arch]}

{training_block(loss, arch)}"""


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for arch in TRANSLATOR_BLOCKS:
        for loss in LOSSES:
            for pool in POOLINGS:
                name = f"{arch}_{loss}_{pool}.toml"
                (OUT_DIR / name).write_text(make_config(arch, loss, pool))
                written.append(name)
    print(f"Wrote {len(written)} configs to {OUT_DIR}/")
    for n in written:
        print(f"  {n}")


if __name__ == "__main__":
    main()
