#!/usr/bin/env python3
"""Generate the compound-loss training sweep configs.

Matrix: translator arch {mlp, encoder, flow, sae} x loss COMBINATION
        x token pooling {last}  =  4 x len(LOSS_COMBOS) configs,
        written to config/loss_combos/.

This is the "compound loss" baseline: instead of training each translator on a
single coordinate loss (mse | cosine | info_nce, as in the FineWeb sweep), we
train on WEIGHTED COMBINATIONS of them. The trainer already supports this via
`losses = [...]` + `loss_weights = [...]`; this generator just emits the configs.

Everything else (models, layer, data_dir, output_dir, epochs, ...) is IDENTICAL
to config/fineweb so:
  - the SAME activation caches under data/fineweb/activations/ are reused
    (no re-extraction needed), and
  - the checkpoints land in outputs/fineweb/ with names like
        best_translator__..__mlp__mse+cosine+info_nce.pt
    (the loss tag is the '+'-joined loss names — see acttrans/utils/paths.py), so
    run_ab_sweep.py's glob `outputs/fineweb/best_translator__*.pt` picks them up
    alongside the single-loss checkpoints automatically.

Only last-token pooling is emitted here to keep the matrix small. To also sweep
mean-pooling, add "mean" to POOLINGS below (this DOUBLES the config count and
requires the mean activation caches to exist).

Re-run this script any time to regenerate the configs from scratch.
"""

from pathlib import Path

from sweep_common import LIMIT, TRANSLATOR_BLOCKS, base_blocks, training_block

OUT_DIR = Path(__file__).resolve().parent / "loss_combos"

# ---------------------------------------------------------------------------
# The compound-loss matrix. Each entry is (list_of_loss_names, list_of_weights).
# Weights are per-loss coefficients applied inside the trainer's `criterion`
# (loss = sum(w_i * loss_i)). To add a future relational loss (e.g. "vsp"),
# simply append a new tuple here, e.g.
#     (["mse", "vsp"], [1.0, 1.0]),
# once the trainer's _make_loss_fn knows how to build it. Nothing else changes:
# the checkpoint name / A/B glob pick up the new '+'-joined tag automatically.
#
# Weight rationale: mse is on a raw-magnitude scale while cosine/info_nce are
# bounded ~O(1); on L2-normalized activations (normalize_activations = true)
# all three sit at comparable scales, so equal 1.0 weights are a sane baseline.
# ---------------------------------------------------------------------------
LOSS_COMBOS = [
    (["mse", "cosine"], [1.0, 1.0]),
    (["mse", "info_nce"], [1.0, 1.0]),
    (["cosine", "info_nce"], [1.0, 1.0]),
    (["mse", "cosine", "info_nce"], [1.0, 1.0, 1.0]),
]

# Token pooling. Keep to {last} by default; add "mean" to also sweep mean-pooled
# (doubles the matrix and needs the *_mean activation caches).
POOLINGS = {"last": "-1"}  # token_position value, verbatim TOML


def combo_slug(loss_names) -> str:
    """Filename-safe tag: '+'-joined loss names (matches the checkpoint loss_tag)."""
    return "+".join(loss_names)


def make_config(arch: str, loss_names, loss_weights, pool: str) -> str:
    tag = combo_slug(loss_names)
    return f"""# AUTO-GENERATED by config/generate_loss_combo_configs.py — do not edit by hand.
# Compound-loss sweep: translator={arch}  losses={tag}  token={pool}
# Shared FineWeb split (sample-10BT, seed 42, limit {LIMIT}); reuses data/fineweb activation caches.

{base_blocks(POOLINGS[pool])}
[translator]
{TRANSLATOR_BLOCKS[arch]}

{training_block(loss_names, loss_weights, arch,
                "checkpoints land beside the single-loss ones (shared A/B glob)",
                "sentences.json + activation caches (shared with the fineweb sweep)")}"""


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for arch in TRANSLATOR_BLOCKS:
        for loss_names, loss_weights in LOSS_COMBOS:
            for pool in POOLINGS:
                name = f"{arch}_{combo_slug(loss_names)}_{pool}.toml"
                (OUT_DIR / name).write_text(
                    make_config(arch, loss_names, loss_weights, pool)
                )
                written.append(name)
    print(f"Wrote {len(written)} configs to {OUT_DIR}/")
    for n in written:
        print(f"  {n}")


if __name__ == "__main__":
    main()
